### ISSUE TITLE
MongoDB Auth Error

### ISSUE THREAD

**Issue by Mordoxo** [AmitKumarHQ/AI-Moderation#2]
PS C:\Users\tortu\Desktop\AI-Moderation-master> npm run start
npm WARN config global --global, --local are deprecated. Use --location=global instead.

ai-moderation@1.0.0 start
node dist/main.js

╭───────────────────────────────────────────────────────────────────╮
│ │
│ Discord.js: v14.1.2 │
│ │
│ Events: OK │
│ Commands: OK │
│ Database: MongoServerError: bad auth : Authentication failed. │
│ │
╰───────────────────────────────────────────────────────────────────╯

my console said this when i started the bot, how can i fix it?

**Comment by amitkumarhq** [comment]
You need to change add your **VALID** MongoDB Database URL/URI (Atlas in my case) in the [config.ts](https://github.com/AmitKumarHQ/AI-Moderation/blob/master/src/config.ts#L6).
Also make sure you whitelist your IP in MongoDB Dashboard | Network Access

After adding the correct URI, it should look something like this
```ts
Database: {
    /* Replace: 
        - <password> with your database password
        - DB_NAME with your database name
    */
    MongoDB: 'mongodb+srv://DB_NAME:<password>@DB_NAME.zozta.mongodb.net/?retryWrites=true&w=majority',
},
```
